import type {Metadata} from "next";
import "./globals.css";
import Header from "./../components/header";
import Footer from "@/components/footer";
import { DataProvider } from '@/services/dataProvider';
import {Component} from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
     children,
 }: Readonly<{
    children: React.ReactNode;
}>, pageProps) {
    return (
        <html lang="en">
        <body>
        <Header/>
        <DataProvider>
            {children}
        </DataProvider>
        <Footer/>
        </body>
        </html>
    );
}
